// <auto-generated />
using System;
using Claims_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Claims_System.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20251021114543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Claims_System.Models.LecturerClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinatorStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Document1FileData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Document1FileName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Document2FileData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Document2FileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("REAL");

                    b.Property<string>("ManagerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClaimId");

                    b.ToTable("LecturerClaims");
                });

            modelBuilder.Entity("Claims_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            EmployeeNumber = 1001,
                            PasswordHash = "pass123",
                            Username = "lecturer1"
                        },
                        new
                        {
                            UserId = 2,
                            EmployeeNumber = 2001,
                            PasswordHash = "admin123",
                            Username = "coordinator1"
                        },
                        new
                        {
                            UserId = 3,
                            EmployeeNumber = 1002,
                            PasswordHash = "pass456",
                            Username = "lecturer2"
                        },
                        new
                        {
                            UserId = 4,
                            EmployeeNumber = 3001,
                            PasswordHash = "manager123",
                            Username = "manager1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
